### ISSUE TITLE
Could not find "store" in either the context or props of "Connect(WithStyles(Layout))"

### ISSUE THREAD

**Issue by tanobi92** [MacKentoch/react-redux-nextjs-material-ui-pwa-starter#1]
Hi @MacKentoch ,
I run your code, It have an error: 
```
Automatic fallback to connect has been performed, please check your code.
{ Invariant Violation: Could not find "store" in either the context or props of "Connect(WithStyles(Layout))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Con
nect(WithStyles(Layout))".
    at invariant (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\invariant\invariant.js:42:15)
    at new Connect (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\react-redux\lib\components\connectAdvanced.js:134:33)
    at resolve (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:2100:14)
    at ReactDOMServerRenderer.render (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:2234:19)
    at renderToString (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\react-dom\cjs\react-dom-server.node.development.js:2501:25)
    at Object.renderPage (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\next\dist\server\render.js:174:26)
    at Function._callee$ (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\pages\_document.js:56:21)
    at tryCatch (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\WORK\Libs\react-redux-nextjs-material-ui-pwa-starter-master\node_modules\regenerator-runtime\runtime.js:296:22) name: 'Invariant Violation', framesToPop: 1 }


```
How to fix it? Thanks!

**Comment by MacKentoch** [comment]
Hi @tanobi92 

My mistake. 

Explanations: when connecting a NextJS app. To redux, use `withRedux`(*which contains the provider*) just for pages. And others components should be connected via regular `connect` from `react-redux`.

**Comment by MacKentoch** [comment]
I updated the starter to fix it and use compose (since a bit too many HOC) to make code cleaner.

**Comment by tanobi92** [comment]
Thanks @MacKentoch :D
